---
title: "gt summary t-test and ANOVA examples"
output: html_document
---

```{r setup}
library(gtsummary)
library(palmerpenguins)
library(tidyverse)
library(autoReg)
theme_gtsummary_mean_sd()  #https://www.danieldsjoberg.com/gtsummary/reference/theme_gtsummary.html
```

```{r t test}
tbl_summary(trial, by = trt) %>%
  add_p(age ~ "t.test", test.args = age ~ list(var.equal = FALSE)) #uses Welch's unequal variance t-test
```

```{r ANOVA}
tbl_summary(trial, by = trt) %>%
  add_p(age ~ "aov") #see example above using t.test to compare two groups (more appropriate)
```

```{r iris ANOVA}
tbl_summary(iris, by = Species) %>%
  add_p(Sepal.Length ~ "aov") #ANOVA is appropriate test for 3 groups
#not sure why it includes all columns by default; use 'select' if you want fewer columns
```

```{r penguins ANOVA}
#probably the most straight forward example

birds <- penguins %>% 
  select(species, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g)

tbl_summary(birds, by = species, missing = "no") %>%
  add_p(all_continuous() ~ "aov") %>%
  # add a header (which also unhides a hidden column)
  # modify_header(statistic ~ "**Test Statistic**") %>%
  # add a function to format the column
  # modify_fmt_fun(statistic ~ style_sigfig)
  add_q(method = "fdr")

#there is still a bug in the suggested way to insert test statistics (commented out)
#https://stackoverflow.com/questions/69606149/how-do-i-display-test-statistic-f-value-for-anova-using-tbl-summary
```

https://stackoverflow.com/questions/61605923/how-to-generate-t-value-f-value-or-chi-square-in-the-summary-table-using-r-pack

```{r Using autoReg}
library(autoReg)
autoReg::gaze(species~.,data=birds)
```
https://cardiomoon.github.io/autoReg/articles/Statiastical_test_in_gaze.html

```{r make publication quality with flextable}
#make publication quality with flextable
autoReg::gaze(species~.,data=birds) %>% myft()
```

You can add labels to the names of variables with `setLabel()` function.

```{r add labels to gaze flextable}

birds$bill_length_mm=setLabel(birds$bill_length_mm,"Bill Length (mm)")
birds$bill_depth_mm=setLabel(birds$bill_depth_mm,"Bill Depth (mm)")
birds$flipper_length_mm=setLabel(birds$flipper_length_mm,"Flipper Length (mm)")
birds$body_mass_g=setLabel(birds$body_mass_g,"Body Mass (g)")

autoReg::gaze(species~.,data=birds) %>%  #. means 'all other variables'
  autoReg::myft()%>% #converts dataframe to a flextable
  flextable::save_as_docx(path = "Figs/Table2_flextable.docx")
```

```

