---
title: "Table 1 using gtsummary"
author: "CM Gienger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(gt)
library(gtsummary)
library(Rmisc)
library(tidyverse)
library(flextable)

data <- read_csv("../data/shelter_attributes.csv")
```

```{r select variables}
data_summary2 <- data %>% 
  dplyr::select(Treatment, Height, Width, Depth, Roof, Floor, `Logger Depth`) #grouping variable and measurement variables
  
#notice that I had to use back ticks to surround variable containing space
#spaces in variable names is bad practice
```

```{r make summary table with gtsummary, message=FALSE, warning=FALSE}
data_summary2 %>%
  tbl_summary(by = Treatment) %>%
  add_p()
```

```{r second summary}
#sometimes you have to force continuous variables into the proper format
#https://stackoverflow.com/questions/67388749/r-tbl-summary-treating-continuous-variables-correctly

table1 <- 
  data_summary2 %>%
  tbl_summary(
    type = list(where(is.numeric) ~ "continuous"), #forces all numeric variables to be continuous
    by = Treatment,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} / {N}"
    ),
    digits = all_continuous() ~ 1,
    label = list(Width ~ "Width (cm)",       #add units to row labels
              Height ~ "Height (cm)",
              Depth ~ "Depth (cm)",
              `Logger Depth` ~ "Logger Depth (cm)"),
    missing_text = "(Missing)"
  ) %>%
  add_p()

table1
```

```{r show current values of the header}
show_header_names(table1)
```

```{r modify table}
#remove sample size report (N) and superscripts
table1 <- table1 %>%
  modify_header(label = '**Attribute**',
  stat_1 = '**Actual**',
  stat_2 = '**Potential**',
  stat_3 = '**Random**',
  p.value = '**p-value**') %>%
  modify_footnote(everything() ~ NA) #gets rid of superscripts and footnotes; put them in table caption instead.

table1
#now you have a very clean table; most journals do not permit superscripts in tables.
#Can put details of statistical tests in Table caption
#after exporting to word processing program.

#post-hoc comparisons among groups not supported currently in gtsummary; might be able to do that manually in gt
```

```{r export table to docx}
#table1 %>% 
  #as_gt() %>%
  #gt::gtsave("Figs/tab_1.docx")
##cannot open the .docx document; corrupted?
## maybe not supported: https://www.danieldsjoberg.com/gtsummary/articles/rmarkdown.html
```

```{r export table to rtf}
#table1 %>% 
  #as_gt() %>%
  #gt::gtsave("figs/tab_1.rtf")
##works but ugly as sin
```

```{r export table to docx via flextable}
table1 %>%
  as_flex_table() %>%
  flextable::save_as_docx(path = "../figs/table1_flextable.docx")
```
