---
title: "t-test of lizard morphometrics"
author: "C.M. Gienger"
date: "2023-09-12"
output: html_document
---

```{r setup, warning = FALSE, message = FALSE}
library(tidyverse)
library(gtsummary)
library(palmerpenguins)
```

```{r data import, message=FALSE, warning=FALSE}
draco_ecomorph1 <- read_csv("../data/draco_ecomorph.csv")
##.. means look up one level for the 'data'folder
```

```{r set builtin theme}
theme_gtsummary_mean_sd(set_theme = TRUE)
#Sets default summary statistics to mean and standard deviation in tbl_summary()
#Sets default continuous tests in add_p() to t-test and ANOVA
```

```{r t-test example make the table}
#this function works best with datasets without NA values

table_Draco2 <- draco_ecomorph1 %>%
  filter(species =="bimaculatus") %>%
  select(sex, snout_vent_length_mm, tail_length_mm, fore_limb_length_mm, fore_toe_length_mm, perch_height_cm) %>% 
  #retain specific variables used in summaries rather than using all
  tbl_summary(
    by = sex,
    missing = "no",
    # remove missing values (NAs). "ifany" will include a missing values row in table.
    digits = all_continuous() ~ 1,
    #number of displayed digits for continuous variables
    label = list(
      snout_vent_length_mm ~ "SVL (mm)",
      tail_length_mm ~ "Tail Length (mm)",
      fore_limb_length_mm ~ "Forelimb Length (mm)",
      fore_toe_length_mm ~ "Foretoe Length (mm)",
      perch_height_cm ~ "Perch Height (cm)"
    ),
    statistic = list(all_continuous() ~ "{mean} ({sd})", #can use any character for parentheses
                     all_categorical() ~ "{n}")
  ) %>% #count obs. for categorical variables
  add_p(pvalue_fun = ~ style_pvalue(.x, digits = 2)) %>% #number of digits displayed for p-values
  modify_caption("Table 1. *Draco bimaculatus* Morphological Characteristics") %>%
  #modify_header(update = all_stat_cols() ~ "**{level}**") %>% #headers to only contain name of sex
  modify_header(
    update = list(
      label ~ '',
      stat_1 ~ '**Female**', #is markdown **bold** formatting
      stat_2 ~ '**Male**',
      p.value ~ '**P-value**')
  )

#show_header_names(table_Draco) 
#lets you preview code for changing header names and formatting  
                
table_Draco2
```

```{r modify table}
#remove sample size report (N) and superscripts
table_Draco2 <- table_Draco2 %>%
  modify_header(label = 'Measurement',
  stat_1 = 'Female',
  stat_2 = 'Male',
  statistic ~'t-value',
  p.value = 'p-value') %>%
  modify_footnote(everything() ~ NA) %>% #gets rid of superscripts and footnotes; put them in table caption.
  modify_caption("") %>% #blank caption above table
  modify_fmt_fun(statistic ~ style_sigfig)

table_Draco2
#now you have a very clean table; most journals do not permit superscripts in tables.
#Can put details of statistical tests in Table caption
#after exporting to word processing program.
```

```{r export morph table to docx via flextable}
table_Draco2 %>%
  as_flex_table() %>%
  flextable::save_as_docx(path = "../figs/table_ttest_flextable.docx")
```

